# Generated by Django 4.2.5 on 2023-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_amount_remove_payment_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now=True, verbose_name='дата оплаты'),
        ),
    ]
