# Generated by Django 4.2.5 on 2023-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_lesson_options_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='цена'),
        ),
    ]
